apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: my-cloud-native-repo
        image: 779846818072.dkr.ecr.ap-south-1.amazonaws.com/my-cloud-native-repo:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: my-ecr-secret
